create or replace 
FUNCTION GET_ALL_CUSTOMERS
  RETURN SYS.ODCIVARCHAR2LIST
AS
  customer_array SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST(); -- Создание пустого массива
BEGIN
  FOR CUSTOMER_REC IN (
  SELECT  CUSTOMERS.CUSTOMER_ID,
          CUSTOMERTYPES.CUSTOMER_TYPE_NAME,
          CUSTOMERS.CUSTOMER_NAME,
          CUSTOMERS.COUNTRY,
          CUSTOMERS.EMAIL
          FROM CUSTOMERS INNER JOIN CUSTOMERTYPES 
          on CUSTOMERTYPES.CUSTOMER_TYPE_ID = CUSTOMERS.CUSTOMER_ID
  ) LOOP
    CUSTOMER_ARRAY.EXTEND;
    CUSTOMER_ARRAY(CUSTOMER_ARRAY.LAST) := CUSTOMER_REC.CUSTOMER_ID || ',' || 
    CUSTOMER_REC.CUSTOMER_TYPE_NAME || ',' || CUSTOMER_REC.CUSTOMER_NAME || ',' || 
    CUSTOMER_REC.COUNTRY || ',' || CUSTOMER_REC.EMAIL;
  END LOOP;
  
  RETURN customer_array;
END;